services:
    db:
        container_name: db
        image: postgres:12.4-alpine
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: trytofindme
            POSTGRES_DB: db
        ports:
            - 5432:5432

    adminer:
        container_name: adminer
        image: adminer:4.7.8
        restart: always
        ports:
            - 5051:8080
